### ISSUE TITLE
Manjaro-ARM-minimal-vim2-21.10 dies after pacman -Syu

### ISSUE THREAD

**Issue by S-trace** [manjaro-arm/vim2-images#9]
Hello.

I have a `VIM2.V12.3G.8C.emmc.58GB` board and using Krescue-a3a06c-VIM2

I have installed `Manjaro-ARM-minimal-vim2-21.10` on my VIM2 via Krescue's "Online Scripts" `Manjaro-Linux-install.sh` (REL=p10 from 20210912) - it booted up fine.
But when I tried to update the system it became unbootable with the following error:
```
Scanning mmc 2:1...
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Scanning disk mmc@70000.blk...
Disk mmc@70000.blk not ready
Scanning disk mmc@72000.blk...
Disk mmc@72000.blk not ready
Scanning disk mmc@74000.blk...
Found 3 disks
No EFI system partition
BootOrder not defined
EFI boot manager: Cannot load any image
```
Update log, correct boot log before the upgrade, and failed boot log after the upgrade is attached. 

I tried to install Manjaro-ARM-minimal-vim2-21.12 and Manjaro-ARM-minimal-vim2-20211227 using the same script (just changed version), but it does not boot right after installation (with the same error).

I debugged this issue and found the /boot/extlinux/extlinux.conf is removed during the update. 
I restored the original content of extlinux.conf and the system successfully booted after the upgrade (original extlinux conf is attached).

[extlinux.conf.txt](https://github.com/manjaro-arm/vim2-images/files/7831179/extlinux.conf.txt)
[20.10_boot_log_ok.txt](https://github.com/manjaro-arm/vim2-images/files/7831181/20.10_boot_log_ok.txt)
[20.12_boot_log_failure.txt](https://github.com/manjaro-arm/vim2-images/files/7831182/20.12_boot_log_failure.txt)
[upgrade_log.txt](https://github.com/manjaro-arm/vim2-images/files/7831184/upgrade_log.txt)

Could you please fix this issue?

Thank you.

**Comment by spikerguy** [comment]
This is not an issue from Manjaro side instead the kresue side issue. 

Please follow this process and then it will not have issue. 
https://forum.khadas.com/t/installing-manjaro-kde-plasma-21-2rc1-to-emmc-how/14203/13?u=spikerguy


I have informed krescue developer not to use bootscripts method images in krescue with manual changes.   I will try to provide him with mainline uboot images but again he uses a single image for all vims and ofcourse full system update will break the boot process.

**Comment by S-trace** [comment]
I have reinstalled the system following the guide you linked and it seems OK after `pacman -Syu`.
I used `VIM2-Android-TV-SC_VIM2_USER_ATV-v1.0-20200731` to install Android, it has `U-Boot 2015.01-gdf4c3cf9c5-dirty (Jul 31 2020 - 23:08:55)`.

Thank you!
